import { NextRequest, NextResponse } from "next/server";
import { getSessionUserId, getActiveLeague } from "@/lib/session";
import { getLeagueMembers } from "@/lib/leagues";
import { getReadModel } from "@/lib/aggregate";
import { getProvider } from "@/lib/football-api/provider";
import { winProbability, asPercent } from "@/lib/odds";
import { matchPreview, aiConfigured } from "@/lib/ai";
import { chrome } from "@/lib/display";

export const dynamic = "force-dynamic";

// AI match preview — built server-side from real context (teams, odds, who's
// backing whom), then generated by Claude. Returns {text} or 204 when AI isn't
// configured / nothing to say, so the client can hide the section.
export async function GET(req: NextRequest) {
  const userId = await getSessionUserId();
  if (!userId) return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  if (!aiConfigured()) return new NextResponse(null, { status: 204 });

  const matchId = req.nextUrl.searchParams.get("matchId");
  if (!matchId) return NextResponse.json({ error: "matchId required" }, { status: 400 });

  const match = await getProvider().getMatch(matchId);
  if (!match) return NextResponse.json({ error: "not found" }, { status: 404 });

  const league = await getActiveLeague(userId);
  const members = league ? await getLeagueMembers(league.id) : [];
  const model = await getReadModel(league ? { leagueId: league.id } : { restrictUserIds: [userId] });

  const home = model.teamById.get(match.homeTeamId);
  const away = model.teamById.get(match.awayTeamId);
  if (!home || !away) return new NextResponse(null, { status: 204 });

  const prob = asPercent(
    winProbability(
      model.standings.find((s) => s.teamId === match.homeTeamId),
      model.standings.find((s) => s.teamId === match.awayTeamId),
      match.stage !== "group",
    ),
  );

  // Who's backing whom — from each member's predicted winner on this match.
  const picks: string[] = [];
  for (const m of members) {
    const p = model.predictions.find((x) => x.userId === m.id && x.matchId === matchId);
    if (!p) continue;
    const side =
      p.predictedWinnerTeamId === home.id ||
      (p.predictedWinnerTeamId == null && (p.predictedHomeScore ?? 0) > (p.predictedAwayScore ?? 0))
        ? home.shortName ?? home.name
        : p.predictedWinnerTeamId === away.id ||
            (p.predictedWinnerTeamId == null && (p.predictedAwayScore ?? 0) > (p.predictedHomeScore ?? 0))
          ? away.shortName ?? away.name
          : "a draw";
    picks.push(`${chrome(m).name} → ${side}`);
  }

  const text = await matchPreview({
    // Cache by match + the picks that feed the preview, so it refreshes if picks change.
    cacheKey: `${matchId}:${picks.join(",")}`,
    home: home.shortName ?? home.name,
    away: away.shortName ?? away.name,
    stage: match.stage.replace(/_/g, " "),
    homeWinPct: prob.home,
    drawPct: prob.draw,
    awayWinPct: prob.away,
    picks,
  });

  if (!text) return new NextResponse(null, { status: 204 });
  return NextResponse.json({ text });
}
